package ResourceCommunication;


/**
* ResourceCommunication/CoordinatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ResourceCommunication.idl
* Quinta-feira, 26 de Janeiro de 2017 12h28min05s GFT
*/

public interface CoordinatorInterface extends CoordinatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CoordinatorInterface
