package ResourceCommunication;


/**
* ResourceCommunication/ProcessInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ResourceCommunication.idl
* Quinta-feira, 26 de Janeiro de 2017 12h28min05s GFT
*/

public interface ProcessInterfaceOperations 
{
  void concedeResource ();
} // interface ProcessInterfaceOperations
