package ProcessResourceCommunication;

/**
* ProcessResourceCommunication/ProcessInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProcessResourceCommunication.idl
* Sexta-feira, 27 de Janeiro de 2017 12h08min34s GFT
*/

public final class ProcessInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ProcessResourceCommunication.ProcessInterface value = null;

  public ProcessInterfaceHolder ()
  {
  }

  public ProcessInterfaceHolder (ProcessResourceCommunication.ProcessInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProcessResourceCommunication.ProcessInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProcessResourceCommunication.ProcessInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProcessResourceCommunication.ProcessInterfaceHelper.type ();
  }

}
