package ProcessResourceCommunication;


/**
* ProcessResourceCommunication/ProcessInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProcessResourceCommunication.idl
* Sexta-feira, 27 de Janeiro de 2017 12h08min34s GFT
*/

public interface ProcessInterfaceOperations 
{
  void concedeResource ();
} // interface ProcessInterfaceOperations
