module ResourceCommunication{
	interface ProcessInterface{
        void concedeResource();
	};

	interface CoordinatorInterface{
        void requestResource (in string pId);
        void releaseResource ();
	};
};
